### ISSUE TITLE
[v1.0] Performance Testing

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#104]
- [x] CNN
    - [x]  sota nas baseline(projection) -> done
    - [x] CNN DeNas (random search)
    - [x] CNN DeNas (EA)
- [x] NLP
    - [x] stock NLP
    - [x] NLP DeNas
- [x] ASR
    - [x] stock ASR
    - [x] ASR DeNas 
- [x] VIT
    - [x] stock VIT
    - [x] VIT DeNas

@Peach-He

**Comment by Peach-He** [comment]
update performance status:

* For performance over SOTA NAS, DENAS CNN delivered 40.73x search and 82.57x training speedup over SOTA NAS (ZenNAS) with 38% model size reduction and 5% accuracy loss  (0.91 vs. 0.9579). DENAS ViT delivered 35.63x search and 4.44x training speedup over SOTA NAS (AutoFormer) with 5% accuracy loss (0.90 vs. 0.9482)
* For performance over stock model, DENAS CNN, ViT, NLP and ASR delivered 9.86x, 4.44x, 7.68x and 59.12x training speedup over ResNet50, AutoFormer, Bert-base and RNN-T
* For search strategy, spearman rank correlation efficient is 0.559510567 for NLP domain
