### ISSUE TITLE
[v1.0] CV CI/CD refine

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#137]
- [x] move UT in https://github.com/intel/e2eAIOK/blob/main/tests/unittest/test_denas_cv_trainer.py to CI/CD corresponding model

@zigzagcai

**Comment by zigzagcai** [comment]
Refined in https://github.com/intel/e2eAIOK/pull/140 and https://github.com/intel/e2eAIOK/pull/139

**Comment by zigzagcai** [comment]
For DeNas CNN training, CI tests added here:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/8370601/208694159-ea8aaa1b-12c6-48bf-bfc8-76353c38b401.png">
For DeNas ViT training, CI tests added here
<img width="928" alt="image" src="https://user-images.githubusercontent.com/8370601/208694492-7ed1b067-422a-41c0-a96c-bfbd5e35bf17.png">

**Comment by xuechendi** [comment]
@zigzagcai , close this issue for completion
