### ISSUE TITLE
[v1.1] DE-NAS HG transfomer API integration 

### ISSUE THREAD

**Issue by Jian-Zhang** [intel/e2eAIOK#183]
- [x]  Design 
- [x]  Search code 
- [x]  Trainer 
- [x]  UT & Function Tests 
- [x]  simplifiy config
- [x]  use model name to indicate workflow

**Comment by xuechendi** [comment]
Added some todo comments:
1.	design doc on different path for denas-search get_latency function, we currently have 3 domain and 4 models, which create 12 combination. After huggingface support, it will continue grow, we need to find a better way here. Suggested to use a single point function with dictionary.
2.	Get_latency re-org (design doc) -> PR
3.	Structure layer/keywork name -> list (design doc) -> PR
4.	Continue on PR (183)
