### ISSUE TITLE
[v1.2] DE-NAS Pruner development

### ISSUE THREAD

**Issue by Peach-He** [intel/e2eAIOK#184]
- [ ] Design doc
- [ ] Pruner implementation
- [ ] DE-NAS search integration
- [ ] Trainer
- [ ] CICD, UT

**Comment by xuechendi** [comment]
Some detailed todo:
1.	Separate current asr denas fixing to another new PR. We can merge that firstly.
2.	design doc on denas-search with pruner or supernet, currently codes is doing switch in asr_is_legal, this will potential create another 3 switch in other domain, so we should uplevel asr_is_legel function to is_legal, and add pruner / supernet switch there.
3.	re-fine denas-search codes to add pruner path -> PR
4.	Continue on PR 181
