### ISSUE TITLE
[v1.2]MA Domain Adapter NLP workflow with HG transformer 

### ISSUE THREAD

**Issue by zhouyu5** [intel/e2eAIOK#199]
- [x] Design doc
- [ ] Code implementation
    - [x] Domain Pre-training
    - [ ] Data selection
    - [ ] Tokenizer Augmentation
    - [x] Workflow scripts
    - [x] DE-NAS integration support
- [x] Benchmark
    - [x] Benchmark on CPU
    - [x] Performance Test on target machine
- [ ] Doucument
    - [ ] Readme
    - [ ] click-to-run Demo
- [ ] Code Test
    - [ ] CICD
    - [ ] UT

**Comment by xuechendi** [comment]
@zhouyu5 @XinyaoWa , please check if TODOs here are all closed

**Comment by zhouyu5** [comment]
> @zhouyu5 @XinyaoWa , please check if TODOs here are all closed

Completed tasks are marked. Will finish the remaining tasks until next release.
