### ISSUE TITLE
[v0.2.1] update tensorflow to 2.10

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#34]

**Comment by xuechendi** [comment]
@zigzagcai , let's directly contribute to here

**Comment by xuechendi** [comment]
@zigzagcai , can you add TF PR link here and close this issue?

**Comment by zigzagcai** [comment]
This issue is fixed by [PR](https://github.com/intel/e2eAIOK/pull/50)

**Comment by zigzagcai** [comment]
> @zigzagcai , can you add TF PR link here and close this issue?



> @zigzagcai , can you add TF PR link here and close this issue?

TF PR link is added here. The issue can be closed but I don't have the permission to close it.
