### ISSUE TITLE
[v1.2] Feature request to allow user to set execution engine

### ISSUE THREAD

**Issue by adkakne** [intel/e2eAIOK#445]
Hi team, 

Can we allow user to set the execution engine either during creation of pipeline object or during call to pipeline.execute function?

Using ray as default is causing more memory issues than spark while dealing with large parquet files. Thank you.

**Comment by xuechendi** [comment]
@haojinIntel , will you help to impl for this issue.

**Comment by haojinIntel** [comment]
Have supported the feature on this PR https://github.com/intel/e2eAIOK/pull/447

**Comment by xuechendi** [comment]
PR #477 is merged.

**Comment by adkakne** [comment]
Thanks a lot, Chendi and Haojin.
