### ISSUE TITLE
[v1.0]Unit Test

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#61]
- [x] put none hardware-related unittest on travis
- [x] add UT for DeNas module
- [x] add test for installation process
    - [x] test pip
    - [x] test  run_e2eaiok_docker.py
@zigzagcai @Peach-He 
Due Date:
Plan done by WW48.2
Codes done by WW49.2

**Comment by xuechendi** [comment]
@zigzagcai

**Comment by zigzagcai** [comment]
- For hardware-related unittest, we have added initial Travis unittest framework. Works well with folder `pytest tests/unittest`

**Comment by zigzagcai** [comment]
Partially completed in https://github.com/intel/e2eAIOK/pull/111

**Comment by zigzagcai** [comment]
For DeNas UT, we will gradually add DeNas unittest later.

**Comment by zigzagcai** [comment]
Complted.
https://github.com/intel/e2eAIOK/pull/114
