### ISSUE TITLE
[v0.3] Migrate common libs to e2eAIOK/common

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#73]
This task is to eliminate redundant effort in different modules
suggested to put all common function in here as base class, if there are some funtion/args are designed for specific task, may derive from base class. So we can keep non-common function as less as possible.
Due:
Design done by WW47.2
Codes contributed to e2eAIOK by WW47.5
- [ ] ~~design doc updated - pls attach arch design in this issue~~
- [x] e2eAIOK/common/trainer
- [x] e2eAIOK/common/dataloader
- [x] e2eAIOK/common/utils

@csdingbin @huaxz1986

**Comment by xuechendi** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



e2eaiok |   |   |  
-- | -- | -- | --
  | recdp |   |  
  | e2eaiok |   |  
  |   | Common lib |  
  |   |   | trainer
  |   |   | dataloader
  |   |   | utils
  |   | sda |  
  |   | denas |  
  |   | MA |  



</div>


</body>

</html>

**Comment by huaxz1986** [comment]
OK, I have discussed with Bin, and he will merge his codes to a common interface and I will follow the common interface after his refactoring.

**Comment by csdingbin** [comment]
@xuechendi  Completed the common trainer code implementation. please help to review and merge #84

**Comment by xuechendi** [comment]
completed
