### ISSUE TITLE
[v0.2] Performance PDT 

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#75]
- [x] v0.2 performance PDT -  due by WW47
    - [x] RNNT small scale
    - [x]  ResNet wip software improvement ratio
    - [x] minigo refreshing with RedHat os on CLX
    - [x] Bert
- [x] wait for PDT review

@Peach-He , please update here for latest status

**Comment by xuechendi** [comment]
now send to PDT review comittee

**Comment by xuechendi** [comment]
@Peach-He , please help to update PDT status in this issue

**Comment by Peach-He** [comment]
v0.2 workload training performance: 13.06x, 10.10x, 10.12x and 14.19x for MiniGo, BERT, ResNet and RNN-T. Waiting feedback from PDT reviewers

**Comment by xuechendi** [comment]
@Jian-Zhang , this issue is completed
