### ISSUE TITLE
[v0.3] pip and docker click-to-run

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#76]
- [x] setup.py for e2eaiok/e2eaiok-sda/e2eaiok-denas
- [x] run_e2eaiok_docker for docker env setup

@zigzagcai 

Due Date: WW50

**Comment by zigzagcai** [comment]
Completed. 
https://github.com/intel/e2eAIOK/pull/95

**Comment by zigzagcai** [comment]
- Package All and Install
`python setup.py sdist`
- Pakckage DeNas and Install
`python setup.py sdist --denas`
- Pakcage SDA and Install
`python setup.py sdist --sda`
