### ISSUE TITLE
[v0.3] update pytorch and tensorflow docker to latest

### ISSUE THREAD

**Issue by xuechendi** [intel/e2eAIOK#83]
we target to only support pytorch1.12 and tensorflow 2.10 in v0.3
TODO:

- [x] update DockerfilePytorch -> use oneapi 2022.03(or latest version)
- [x] update DockerfileTensorflow -> use oneapi 2022.03 + tensorflow 2.10
- [ ] ~~remove DockerfilePytorch for mlperf -> need to make sure dlrm still runnable~~ won't do due conflict
- [x] update start_e2eaiok_docker.py

assignee: @zigzagcai 
task due: WW48

**Comment by xuechendi** [comment]
@zigzagcai , please update to this issue once you started to work on this

**Comment by zigzagcai** [comment]
We need to keep the old version PyTorch Dockerfile for DLRM code, sicne DLRM code only works with specific version of packages. 
I have validated DLRM in pytorch1.10, and it cannot run properly.
@xuechendi @Peach-He @csdingbin

**Comment by zigzagcai** [comment]
For Tensorflow, we only keep latest version of TensorFlow Dockerfile.

**Comment by zigzagcai** [comment]
For PyTorch, we provide a seperate DockerfilePytorch120 for DE-NAS and TLK

**Comment by zigzagcai** [comment]
DockerfilePytorch120  works well with DeNas cnn/vit/bert/asr.

**Comment by zigzagcai** [comment]
Please kindly merge [https://github.com/intel/e2eAIOK/pull/80](url) and then merge [https://github.com/intel/e2eAIOK/pull/85](url)

**Comment by xuechendi** [comment]
> Please review and merge [PR#80](https://github.com/intel/e2eAIOK/pull/80) and then merge [PR#85](https://github.com/intel/e2eAIOK/pull/85). Thx @xuechendi

merged https://github.com/intel/e2eAIOK/pull/80 and left some todo for https://github.com/intel/e2eAIOK/pull/85, please fix

**Comment by zigzagcai** [comment]
TODOs have already been fixed.
We need to keep PyTorch1.10 for RNNT, since PyTorch1.20 base image has bugs with oneapi and torchccl.
DockerfilePytorch120 is for DeNas and TLK(in future), and works well.

**Comment by xuechendi** [comment]
This issue is completed
